### ISSUE TITLE
🌍 Feature request

### ISSUE THREAD

**Issue by goldenson** [basecamp/name_of_person#2]
👋 Thanks for this great gem

## Problem

`Name`, `full name` and `initials` are not same all over the world. In countries like 🇯🇵 it's offensive to show `first_name` before `last_name`.

I'm part of the international team @shopify and we decided to tackle those small details in order to offer a better expericence for our merchants.

Here an example of how it looks like:

```ruby
# frozen_string_literal: true
module I18n
  module NameFormatter
    extend self

    EASTERN_NAMING_ORDER_LOCALES = [:ja, :zh, :ko, :km, :vi]

    def full_name(first_name, last_name)
      if EASTERN_NAMING_ORDER_LOCALES.include?(I18n.locale)
        [last_name, first_name].reject(&:blank?).join(" ")
      else
        [first_name, last_name].reject(&:blank?).join(" ")
      end
    end

    def name(first_name, last_name)
      if EASTERN_NAMING_ORDER_LOCALES.include?(I18n.locale)
        last_name
      else
        first_name
      end
    end
  end
end
```

## Solution
> Feel free to fork this library if you'd like to add large upgrades like titulations or different accommodations for other languages.

Saw the Readme but wondering if it would be beneficial to introduce an `i18n` dependency to this gem in order to share the  best practices we developed internally for the rest of the community without to worried about those culture details?

https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

Happy to provide a PR for it 🙏

**Comment by dhh** [comment]
Maxime, I worry that this is a slippery slope for i18n considerations, but
I really appreciate you reaching out about it. And I'm happy to see what a
PR could look like. I don't really want to make i18n a dependency of this,
but we could make it an optional dependency. IF i18n has been loaded, and
if locale is set, then we check for this. Happy to see what that could look
like. Thanks again!

**Comment by jdickey** [comment]
As noted in [the opening comment](issue-372086860), name order and usage varies between cultures and locales, and steamrollering the Western given-name + family-name ordering can be highly offensive in cultures like Japan.

An easy workaround for this is to open a PR that adds a `western_name_order` Boolean parameter to  [`.full`](https://github.com/basecamp/name_of_person/blob/master/lib/name_of_person/person_name.rb#L7-L10) and [`#initialize`](https://github.com/basecamp/name_of_person/blob/master/lib/name_of_person/person_name.rb#L12-L16), default `true`. Setting the value to `false` will cause names in all other instance methods to be rendered in surname-first order, e.g., "Ai Weiwei" rather than "Weiwei Ai".

The PR, in a separate commit, should change the usage of `first_name` and `last_name` to `given_name` and `family_name` respectively. The existing method names may be kept as aliases.

The PR should also change the internal representation of the name such that the *full name* is the associated attribute, with the (possibly memoised) given and family names accessible via methods. This would allow for the (to monolingual English speakers) wild variations summarised in [this W3C note on _Personal names around the world_](https://www.w3.org/International/questions/qa-personal-names) to be properly accounted for.

This suggests an alternative to the "easy workaround" mentioned above: instead of adding a `western_name_order` Boolean parameter, add `family_name_extractor` and `personal_name_extractor` parameters, which are functions/methods that (attempt to) follow the rules appropriate to the current locale to extract the appropriate name segment from the `full_name` value. (This could be done with a [custom i18n backend](https://guides.rubyonrails.org/i18n.html#using-different-backends) for name rules and making use of that custom backend a requirement for correct use of the Gem; I would think that would be a more onerous requirement?

----

Finally, one would expect the `i18n` Gem or Rails i18n (which is built atop the Gem) to support specifying name order. Several hours of reading through source files and related pages has failed to indicate that it has such a feature.

**Comment by dhh** [comment]
This gem is unlikely to see any additional development from my and our side at Basecamp. Exactly because the issues around first and last names, we've decided only to use full names in future products at Basecamp. So we no longer have a need for this.

Anyone is free to fork and continue to the work, though.
